using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("2.17.0")]
[assembly: AssemblyFileVersionAttribute("2.17.0")]
[assembly: AssemblyInformationalVersionAttribute("2.17-DIRTY")]

